// <auto-generated />
namespace ArbiterTown.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class arbiter_numOfExpired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(arbiter_numOfExpired));
        
        string IMigrationMetadata.Id
        {
            get { return "201601052122124_arbiter_numOfExpired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
