// <auto-generated />
namespace responseTip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TaskStatusesEnumclosed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskStatusesEnumclosed));
        
        string IMigrationMetadata.Id
        {
            get { return "201510181114430_TaskStatusesEnum.closed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
